sudo: false
services: mongodb
language: node_js
node_js:
  - "0.10"

before_script:
  - echo "... MongoDB OK"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - protractor e2e-tests/protractor.conf.js
